/*
 * Tradier API
 * Tradier API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.BalancesBalancesMargin;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * BalancesBalances
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-31T14:29:22.511420325Z[GMT]")

public class BalancesBalances {
  @SerializedName("option_short_value")
  private Integer optionShortValue = null;

  @SerializedName("total_equity")
  private BigDecimal totalEquity = null;

  @SerializedName("account_number")
  private String accountNumber = null;

  @SerializedName("account_type")
  private String accountType = null;

  @SerializedName("close_pl")
  private BigDecimal closePl = null;

  @SerializedName("current_requirement")
  private BigDecimal currentRequirement = null;

  @SerializedName("equity")
  private BigDecimal equity = null;

  @SerializedName("long_market_value")
  private BigDecimal longMarketValue = null;

  @SerializedName("market_value")
  private BigDecimal marketValue = null;

  @SerializedName("open_pl")
  private BigDecimal openPl = null;

  @SerializedName("option_long_value")
  private Long optionLongValue = null;

  @SerializedName("option_requirement")
  private BigDecimal optionRequirement = null;

  @SerializedName("pending_orders_count")
  private Integer pendingOrdersCount = null;

  @SerializedName("short_market_value")
  private BigDecimal shortMarketValue = null;

  @SerializedName("stock_long_value")
  private BigDecimal stockLongValue = null;

  @SerializedName("total_cash")
  private BigDecimal totalCash = null;

  @SerializedName("uncleared_funds")
  private BigDecimal unclearedFunds = null;

  @SerializedName("pending_cash")
  private BigDecimal pendingCash = null;

  @SerializedName("margin")
  private BalancesBalancesMargin margin = null;

  public BalancesBalances optionShortValue(Integer optionShortValue) {
    this.optionShortValue = optionShortValue;
    return this;
  }

   /**
   * Get optionShortValue
   * @return optionShortValue
  **/
  @Schema(description = "")
  public Integer getOptionShortValue() {
    return optionShortValue;
  }

  public void setOptionShortValue(Integer optionShortValue) {
    this.optionShortValue = optionShortValue;
  }

  public BalancesBalances totalEquity(BigDecimal totalEquity) {
    this.totalEquity = totalEquity;
    return this;
  }

   /**
   * Get totalEquity
   * @return totalEquity
  **/
  @Schema(description = "")
  public BigDecimal getTotalEquity() {
    return totalEquity;
  }

  public void setTotalEquity(BigDecimal totalEquity) {
    this.totalEquity = totalEquity;
  }

  public BalancesBalances accountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * Get accountNumber
   * @return accountNumber
  **/
  @Schema(description = "")
  public String getAccountNumber() {
    return accountNumber;
  }

  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }

  public BalancesBalances accountType(String accountType) {
    this.accountType = accountType;
    return this;
  }

   /**
   * Get accountType
   * @return accountType
  **/
  @Schema(description = "")
  public String getAccountType() {
    return accountType;
  }

  public void setAccountType(String accountType) {
    this.accountType = accountType;
  }

  public BalancesBalances closePl(BigDecimal closePl) {
    this.closePl = closePl;
    return this;
  }

   /**
   * Get closePl
   * @return closePl
  **/
  @Schema(description = "")
  public BigDecimal getClosePl() {
    return closePl;
  }

  public void setClosePl(BigDecimal closePl) {
    this.closePl = closePl;
  }

  public BalancesBalances currentRequirement(BigDecimal currentRequirement) {
    this.currentRequirement = currentRequirement;
    return this;
  }

   /**
   * Get currentRequirement
   * @return currentRequirement
  **/
  @Schema(description = "")
  public BigDecimal getCurrentRequirement() {
    return currentRequirement;
  }

  public void setCurrentRequirement(BigDecimal currentRequirement) {
    this.currentRequirement = currentRequirement;
  }

  public BalancesBalances equity(BigDecimal equity) {
    this.equity = equity;
    return this;
  }

   /**
   * Get equity
   * @return equity
  **/
  @Schema(description = "")
  public BigDecimal getEquity() {
    return equity;
  }

  public void setEquity(BigDecimal equity) {
    this.equity = equity;
  }

  public BalancesBalances longMarketValue(BigDecimal longMarketValue) {
    this.longMarketValue = longMarketValue;
    return this;
  }

   /**
   * Get longMarketValue
   * @return longMarketValue
  **/
  @Schema(description = "")
  public BigDecimal getLongMarketValue() {
    return longMarketValue;
  }

  public void setLongMarketValue(BigDecimal longMarketValue) {
    this.longMarketValue = longMarketValue;
  }

  public BalancesBalances marketValue(BigDecimal marketValue) {
    this.marketValue = marketValue;
    return this;
  }

   /**
   * Get marketValue
   * @return marketValue
  **/
  @Schema(description = "")
  public BigDecimal getMarketValue() {
    return marketValue;
  }

  public void setMarketValue(BigDecimal marketValue) {
    this.marketValue = marketValue;
  }

  public BalancesBalances openPl(BigDecimal openPl) {
    this.openPl = openPl;
    return this;
  }

   /**
   * Get openPl
   * @return openPl
  **/
  @Schema(description = "")
  public BigDecimal getOpenPl() {
    return openPl;
  }

  public void setOpenPl(BigDecimal openPl) {
    this.openPl = openPl;
  }

  public BalancesBalances optionLongValue(Long optionLongValue) {
    this.optionLongValue = optionLongValue;
    return this;
  }

   /**
   * Get optionLongValue
   * @return optionLongValue
  **/
  @Schema(description = "")
  public Long getOptionLongValue() {
    return optionLongValue;
  }

  public void setOptionLongValue(Long optionLongValue) {
    this.optionLongValue = optionLongValue;
  }

  public BalancesBalances optionRequirement(BigDecimal optionRequirement) {
    this.optionRequirement = optionRequirement;
    return this;
  }

   /**
   * Get optionRequirement
   * @return optionRequirement
  **/
  @Schema(description = "")
  public BigDecimal getOptionRequirement() {
    return optionRequirement;
  }

  public void setOptionRequirement(BigDecimal optionRequirement) {
    this.optionRequirement = optionRequirement;
  }

  public BalancesBalances pendingOrdersCount(Integer pendingOrdersCount) {
    this.pendingOrdersCount = pendingOrdersCount;
    return this;
  }

   /**
   * Get pendingOrdersCount
   * @return pendingOrdersCount
  **/
  @Schema(description = "")
  public Integer getPendingOrdersCount() {
    return pendingOrdersCount;
  }

  public void setPendingOrdersCount(Integer pendingOrdersCount) {
    this.pendingOrdersCount = pendingOrdersCount;
  }

  public BalancesBalances shortMarketValue(BigDecimal shortMarketValue) {
    this.shortMarketValue = shortMarketValue;
    return this;
  }

   /**
   * Get shortMarketValue
   * @return shortMarketValue
  **/
  @Schema(description = "")
  public BigDecimal getShortMarketValue() {
    return shortMarketValue;
  }

  public void setShortMarketValue(BigDecimal shortMarketValue) {
    this.shortMarketValue = shortMarketValue;
  }

  public BalancesBalances stockLongValue(BigDecimal stockLongValue) {
    this.stockLongValue = stockLongValue;
    return this;
  }

   /**
   * Get stockLongValue
   * @return stockLongValue
  **/
  @Schema(description = "")
  public BigDecimal getStockLongValue() {
    return stockLongValue;
  }

  public void setStockLongValue(BigDecimal stockLongValue) {
    this.stockLongValue = stockLongValue;
  }

  public BalancesBalances totalCash(BigDecimal totalCash) {
    this.totalCash = totalCash;
    return this;
  }

   /**
   * Get totalCash
   * @return totalCash
  **/
  @Schema(description = "")
  public BigDecimal getTotalCash() {
    return totalCash;
  }

  public void setTotalCash(BigDecimal totalCash) {
    this.totalCash = totalCash;
  }

  public BalancesBalances unclearedFunds(BigDecimal unclearedFunds) {
    this.unclearedFunds = unclearedFunds;
    return this;
  }

   /**
   * Get unclearedFunds
   * @return unclearedFunds
  **/
  @Schema(description = "")
  public BigDecimal getUnclearedFunds() {
    return unclearedFunds;
  }

  public void setUnclearedFunds(BigDecimal unclearedFunds) {
    this.unclearedFunds = unclearedFunds;
  }

  public BalancesBalances pendingCash(BigDecimal pendingCash) {
    this.pendingCash = pendingCash;
    return this;
  }

   /**
   * Get pendingCash
   * @return pendingCash
  **/
  @Schema(description = "")
  public BigDecimal getPendingCash() {
    return pendingCash;
  }

  public void setPendingCash(BigDecimal pendingCash) {
    this.pendingCash = pendingCash;
  }

  public BalancesBalances margin(BalancesBalancesMargin margin) {
    this.margin = margin;
    return this;
  }

   /**
   * Get margin
   * @return margin
  **/
  @Schema(description = "")
  public BalancesBalancesMargin getMargin() {
    return margin;
  }

  public void setMargin(BalancesBalancesMargin margin) {
    this.margin = margin;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BalancesBalances balancesBalances = (BalancesBalances) o;
    return Objects.equals(this.optionShortValue, balancesBalances.optionShortValue) &&
        Objects.equals(this.totalEquity, balancesBalances.totalEquity) &&
        Objects.equals(this.accountNumber, balancesBalances.accountNumber) &&
        Objects.equals(this.accountType, balancesBalances.accountType) &&
        Objects.equals(this.closePl, balancesBalances.closePl) &&
        Objects.equals(this.currentRequirement, balancesBalances.currentRequirement) &&
        Objects.equals(this.equity, balancesBalances.equity) &&
        Objects.equals(this.longMarketValue, balancesBalances.longMarketValue) &&
        Objects.equals(this.marketValue, balancesBalances.marketValue) &&
        Objects.equals(this.openPl, balancesBalances.openPl) &&
        Objects.equals(this.optionLongValue, balancesBalances.optionLongValue) &&
        Objects.equals(this.optionRequirement, balancesBalances.optionRequirement) &&
        Objects.equals(this.pendingOrdersCount, balancesBalances.pendingOrdersCount) &&
        Objects.equals(this.shortMarketValue, balancesBalances.shortMarketValue) &&
        Objects.equals(this.stockLongValue, balancesBalances.stockLongValue) &&
        Objects.equals(this.totalCash, balancesBalances.totalCash) &&
        Objects.equals(this.unclearedFunds, balancesBalances.unclearedFunds) &&
        Objects.equals(this.pendingCash, balancesBalances.pendingCash) &&
        Objects.equals(this.margin, balancesBalances.margin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(optionShortValue, totalEquity, accountNumber, accountType, closePl, currentRequirement, equity, longMarketValue, marketValue, openPl, optionLongValue, optionRequirement, pendingOrdersCount, shortMarketValue, stockLongValue, totalCash, unclearedFunds, pendingCash, margin);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BalancesBalances {\n");
    
    sb.append("    optionShortValue: ").append(toIndentedString(optionShortValue)).append("\n");
    sb.append("    totalEquity: ").append(toIndentedString(totalEquity)).append("\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    closePl: ").append(toIndentedString(closePl)).append("\n");
    sb.append("    currentRequirement: ").append(toIndentedString(currentRequirement)).append("\n");
    sb.append("    equity: ").append(toIndentedString(equity)).append("\n");
    sb.append("    longMarketValue: ").append(toIndentedString(longMarketValue)).append("\n");
    sb.append("    marketValue: ").append(toIndentedString(marketValue)).append("\n");
    sb.append("    openPl: ").append(toIndentedString(openPl)).append("\n");
    sb.append("    optionLongValue: ").append(toIndentedString(optionLongValue)).append("\n");
    sb.append("    optionRequirement: ").append(toIndentedString(optionRequirement)).append("\n");
    sb.append("    pendingOrdersCount: ").append(toIndentedString(pendingOrdersCount)).append("\n");
    sb.append("    shortMarketValue: ").append(toIndentedString(shortMarketValue)).append("\n");
    sb.append("    stockLongValue: ").append(toIndentedString(stockLongValue)).append("\n");
    sb.append("    totalCash: ").append(toIndentedString(totalCash)).append("\n");
    sb.append("    unclearedFunds: ").append(toIndentedString(unclearedFunds)).append("\n");
    sb.append("    pendingCash: ").append(toIndentedString(pendingCash)).append("\n");
    sb.append("    margin: ").append(toIndentedString(margin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
