/*
 * Tradier API
 * Tradier API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * BalancesBalancesMargin
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-31T14:29:22.511420325Z[GMT]")

public class BalancesBalancesMargin {
  @SerializedName("fed_call")
  private BigDecimal fedCall = null;

  @SerializedName("maintenance_call")
  private BigDecimal maintenanceCall = null;

  @SerializedName("option_buying_power")
  private BigDecimal optionBuyingPower = null;

  @SerializedName("stock_buying_power")
  private BigDecimal stockBuyingPower = null;

  @SerializedName("stock_short_value")
  private BigDecimal stockShortValue = null;

  @SerializedName("sweep")
  private BigDecimal sweep = null;

  public BalancesBalancesMargin fedCall(BigDecimal fedCall) {
    this.fedCall = fedCall;
    return this;
  }

   /**
   * Get fedCall
   * @return fedCall
  **/
  @Schema(description = "")
  public BigDecimal getFedCall() {
    return fedCall;
  }

  public void setFedCall(BigDecimal fedCall) {
    this.fedCall = fedCall;
  }

  public BalancesBalancesMargin maintenanceCall(BigDecimal maintenanceCall) {
    this.maintenanceCall = maintenanceCall;
    return this;
  }

   /**
   * Get maintenanceCall
   * @return maintenanceCall
  **/
  @Schema(description = "")
  public BigDecimal getMaintenanceCall() {
    return maintenanceCall;
  }

  public void setMaintenanceCall(BigDecimal maintenanceCall) {
    this.maintenanceCall = maintenanceCall;
  }

  public BalancesBalancesMargin optionBuyingPower(BigDecimal optionBuyingPower) {
    this.optionBuyingPower = optionBuyingPower;
    return this;
  }

   /**
   * Get optionBuyingPower
   * @return optionBuyingPower
  **/
  @Schema(description = "")
  public BigDecimal getOptionBuyingPower() {
    return optionBuyingPower;
  }

  public void setOptionBuyingPower(BigDecimal optionBuyingPower) {
    this.optionBuyingPower = optionBuyingPower;
  }

  public BalancesBalancesMargin stockBuyingPower(BigDecimal stockBuyingPower) {
    this.stockBuyingPower = stockBuyingPower;
    return this;
  }

   /**
   * Get stockBuyingPower
   * @return stockBuyingPower
  **/
  @Schema(description = "")
  public BigDecimal getStockBuyingPower() {
    return stockBuyingPower;
  }

  public void setStockBuyingPower(BigDecimal stockBuyingPower) {
    this.stockBuyingPower = stockBuyingPower;
  }

  public BalancesBalancesMargin stockShortValue(BigDecimal stockShortValue) {
    this.stockShortValue = stockShortValue;
    return this;
  }

   /**
   * Get stockShortValue
   * @return stockShortValue
  **/
  @Schema(description = "")
  public BigDecimal getStockShortValue() {
    return stockShortValue;
  }

  public void setStockShortValue(BigDecimal stockShortValue) {
    this.stockShortValue = stockShortValue;
  }

  public BalancesBalancesMargin sweep(BigDecimal sweep) {
    this.sweep = sweep;
    return this;
  }

   /**
   * Get sweep
   * @return sweep
  **/
  @Schema(description = "")
  public BigDecimal getSweep() {
    return sweep;
  }

  public void setSweep(BigDecimal sweep) {
    this.sweep = sweep;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BalancesBalancesMargin balancesBalancesMargin = (BalancesBalancesMargin) o;
    return Objects.equals(this.fedCall, balancesBalancesMargin.fedCall) &&
        Objects.equals(this.maintenanceCall, balancesBalancesMargin.maintenanceCall) &&
        Objects.equals(this.optionBuyingPower, balancesBalancesMargin.optionBuyingPower) &&
        Objects.equals(this.stockBuyingPower, balancesBalancesMargin.stockBuyingPower) &&
        Objects.equals(this.stockShortValue, balancesBalancesMargin.stockShortValue) &&
        Objects.equals(this.sweep, balancesBalancesMargin.sweep);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fedCall, maintenanceCall, optionBuyingPower, stockBuyingPower, stockShortValue, sweep);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BalancesBalancesMargin {\n");
    
    sb.append("    fedCall: ").append(toIndentedString(fedCall)).append("\n");
    sb.append("    maintenanceCall: ").append(toIndentedString(maintenanceCall)).append("\n");
    sb.append("    optionBuyingPower: ").append(toIndentedString(optionBuyingPower)).append("\n");
    sb.append("    stockBuyingPower: ").append(toIndentedString(stockBuyingPower)).append("\n");
    sb.append("    stockShortValue: ").append(toIndentedString(stockShortValue)).append("\n");
    sb.append("    sweep: ").append(toIndentedString(sweep)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
