/*
 * Tradier API
 * Tradier API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.PositionsPositionsPosition;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * PositionsPositions
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-31T14:29:22.511420325Z[GMT]")

public class PositionsPositions {
  @SerializedName("position")
  private List<PositionsPositionsPosition> position = null;

  public PositionsPositions position(List<PositionsPositionsPosition> position) {
    this.position = position;
    return this;
  }

  public PositionsPositions addPositionItem(PositionsPositionsPosition positionItem) {
    if (this.position == null) {
      this.position = new ArrayList<PositionsPositionsPosition>();
    }
    this.position.add(positionItem);
    return this;
  }

   /**
   * Get position
   * @return position
  **/
  @Schema(description = "")
  public List<PositionsPositionsPosition> getPosition() {
    return position;
  }

  public void setPosition(List<PositionsPositionsPosition> position) {
    this.position = position;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PositionsPositions positionsPositions = (PositionsPositions) o;
    return Objects.equals(this.position, positionsPositions.position);
  }

  @Override
  public int hashCode() {
    return Objects.hash(position);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PositionsPositions {\n");
    
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
