/*
 * Tradier API
 * Tradier API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.PositionSinglePositions;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PositionSingle
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-31T14:29:22.511420325Z[GMT]")

public class PositionSingle implements InlineResponse200 {
  @SerializedName("positions")
  private PositionSinglePositions positions = null;

  public PositionSingle positions(PositionSinglePositions positions) {
    this.positions = positions;
    return this;
  }

   /**
   * Get positions
   * @return positions
  **/
  @Schema(description = "")
  public PositionSinglePositions getPositions() {
    return positions;
  }

  public void setPositions(PositionSinglePositions positions) {
    this.positions = positions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PositionSingle positionSingle = (PositionSingle) o;
    return Objects.equals(this.positions, positionSingle.positions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(positions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PositionSingle {\n");
    
    sb.append("    positions: ").append(toIndentedString(positions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
