/*
 * Tradier API
 * Tradier API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * ProfileProfileAccount
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-31T14:29:22.511420325Z[GMT]")

public class ProfileProfileAccount {
  @SerializedName("account_number")
  private String accountNumber = null;

  @SerializedName("classification")
  private String classification = null;

  @SerializedName("date_created")
  private OffsetDateTime dateCreated = null;

  @SerializedName("day_trader")
  private Boolean dayTrader = null;

  @SerializedName("option_level")
  private Integer optionLevel = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("last_update_date")
  private OffsetDateTime lastUpdateDate = null;

  public ProfileProfileAccount accountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * Get accountNumber
   * @return accountNumber
  **/
  @Schema(description = "")
  public String getAccountNumber() {
    return accountNumber;
  }

  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }

  public ProfileProfileAccount classification(String classification) {
    this.classification = classification;
    return this;
  }

   /**
   * Get classification
   * @return classification
  **/
  @Schema(description = "")
  public String getClassification() {
    return classification;
  }

  public void setClassification(String classification) {
    this.classification = classification;
  }

  public ProfileProfileAccount dateCreated(OffsetDateTime dateCreated) {
    this.dateCreated = dateCreated;
    return this;
  }

   /**
   * Get dateCreated
   * @return dateCreated
  **/
  @Schema(description = "")
  public OffsetDateTime getDateCreated() {
    return dateCreated;
  }

  public void setDateCreated(OffsetDateTime dateCreated) {
    this.dateCreated = dateCreated;
  }

  public ProfileProfileAccount dayTrader(Boolean dayTrader) {
    this.dayTrader = dayTrader;
    return this;
  }

   /**
   * Get dayTrader
   * @return dayTrader
  **/
  @Schema(description = "")
  public Boolean isDayTrader() {
    return dayTrader;
  }

  public void setDayTrader(Boolean dayTrader) {
    this.dayTrader = dayTrader;
  }

  public ProfileProfileAccount optionLevel(Integer optionLevel) {
    this.optionLevel = optionLevel;
    return this;
  }

   /**
   * Get optionLevel
   * @return optionLevel
  **/
  @Schema(description = "")
  public Integer getOptionLevel() {
    return optionLevel;
  }

  public void setOptionLevel(Integer optionLevel) {
    this.optionLevel = optionLevel;
  }

  public ProfileProfileAccount status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public ProfileProfileAccount type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ProfileProfileAccount lastUpdateDate(OffsetDateTime lastUpdateDate) {
    this.lastUpdateDate = lastUpdateDate;
    return this;
  }

   /**
   * Get lastUpdateDate
   * @return lastUpdateDate
  **/
  @Schema(description = "")
  public OffsetDateTime getLastUpdateDate() {
    return lastUpdateDate;
  }

  public void setLastUpdateDate(OffsetDateTime lastUpdateDate) {
    this.lastUpdateDate = lastUpdateDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProfileProfileAccount profileProfileAccount = (ProfileProfileAccount) o;
    return Objects.equals(this.accountNumber, profileProfileAccount.accountNumber) &&
        Objects.equals(this.classification, profileProfileAccount.classification) &&
        Objects.equals(this.dateCreated, profileProfileAccount.dateCreated) &&
        Objects.equals(this.dayTrader, profileProfileAccount.dayTrader) &&
        Objects.equals(this.optionLevel, profileProfileAccount.optionLevel) &&
        Objects.equals(this.status, profileProfileAccount.status) &&
        Objects.equals(this.type, profileProfileAccount.type) &&
        Objects.equals(this.lastUpdateDate, profileProfileAccount.lastUpdateDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountNumber, classification, dateCreated, dayTrader, optionLevel, status, type, lastUpdateDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProfileProfileAccount {\n");
    
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    classification: ").append(toIndentedString(classification)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    dayTrader: ").append(toIndentedString(dayTrader)).append("\n");
    sb.append("    optionLevel: ").append(toIndentedString(optionLevel)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    lastUpdateDate: ").append(toIndentedString(lastUpdateDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
