/*
 * Tradier API
 * Tradier API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.SymbolLookupSecuritiesSecurity;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * SymbolLookupSecurities
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-31T14:29:22.511420325Z[GMT]")

public class SymbolLookupSecurities {
  @SerializedName("security")
  private List<SymbolLookupSecuritiesSecurity> security = null;

  public SymbolLookupSecurities security(List<SymbolLookupSecuritiesSecurity> security) {
    this.security = security;
    return this;
  }

  public SymbolLookupSecurities addSecurityItem(SymbolLookupSecuritiesSecurity securityItem) {
    if (this.security == null) {
      this.security = new ArrayList<SymbolLookupSecuritiesSecurity>();
    }
    this.security.add(securityItem);
    return this;
  }

   /**
   * Get security
   * @return security
  **/
  @Schema(description = "")
  public List<SymbolLookupSecuritiesSecurity> getSecurity() {
    return security;
  }

  public void setSecurity(List<SymbolLookupSecuritiesSecurity> security) {
    this.security = security;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SymbolLookupSecurities symbolLookupSecurities = (SymbolLookupSecurities) o;
    return Objects.equals(this.security, symbolLookupSecurities.security);
  }

  @Override
  public int hashCode() {
    return Objects.hash(security);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SymbolLookupSecurities {\n");
    
    sb.append("    security: ").append(toIndentedString(security)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
